### PR TITLE
Remove `svgo` entry in `resolutions` field from package.json

### PR DESCRIPTION
**Pull request by gomorizsolt**
Issue #55.

I can't really remember off the top of my head which command/process caused this issue(the issue is lacking, my fault, but dev & build commands work) but as @thisismydesign pointed out it seems to be resolved.

### CODE REVIEW

**Comment by thisismydesign** [comment]
Wouldn't we need to update svgo to the correct version first?

**Comment by thisismydesign** [comment]
Fix is part of the latest release: https://github.com/svg/svgo/releases/tag/v1.3.2

**Comment by gomorizsolt** [comment]
But that's not part of the dependencies.

**Comment by gomorizsolt** [comment]
https://github.com/elrumordelaluz/svgson/blob/master/package.json#L61

**Comment by thisismydesign** [comment]
Isn't the proper solution then to define a min version in resolutions? Otherwise, we're not making sure that this error is resolved. But maybe it isn't our responsibility but the one of using this as a direct dependency.

But since this is a lib and we don't commit yarn.lock I'd argue it's our responsibility (as well). Another approach would be, if we know which direct dependency uses this and if they have set a min requirement for svgo in a certain version, we can set the requirement of the direct dependency.

So I'd propose to set the resolution to `1.3.2` and ask `svgson` to update their dependency to be `> 1.3.2`. If they do, then we can rely on the correct version of `svgson` only.

**Comment by gomorizsolt** [comment]
TIL that the `resolution` field is yarn's feature. :)

https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

However, we're using npm so it's a bit confusing. How could it temporarily resolve the issue? Because `svgson` uses yarn?

> So I'd propose to set the resolution to 1.3.2 and ask svgson to update their dependency to be > 1.3.2. If they do, then we can rely on the correct version of svgson only.

Either way, let's go with your proposal. Given that `svgson` regularly updates their dependencies(e.g. https://github.com/elrumordelaluz/svgson/commit/7cb8e8cd15f151e3d1ea1aa1b2ff139a21b2d497) I believe they're willing to do on request. :)

**Comment by gomorizsolt** [comment]
> However, we're using npm so it's a bit confusing.
> But since this is a lib and we don't commit yarn.lock I'd argue it's our responsibility (as well).

So even `package-lock.json` is omitted from commits. What's the purpose of doing this?

**Comment by gomorizsolt** [comment]
`yarn install` => `svgo@1.3.2`
`npm install` => `svgo@1.3.2`

I don't think we need `resolutions`.

**Comment by thisismydesign** [comment]
> package-lock.json is omitted for some reason

Because this is a package. It will run in different environments, it will be used by others who already have certain dependencies in their project. We must specify a range of dependencies we're compatible with, not exact versions. The lock file is used when e.g. a deployment of a website uses the exact same dependencies as the development version.

yarn/npm install may resolve to different things in different projects. Someone might specific `svgo = 1.3.1` in their package.json and wants to use this package. Then, yarn/npm must warn them that we're only compatible with 1.3.2 and up.

**Comment by thisismydesign** [comment]
https://github.com/elrumordelaluz/svgson/issues/21

**Comment by thisismydesign** [comment]
This isn't an issue with `svgson`, please take a closer look at yarn.lock.

**Comment by thisismydesign** [comment]
Closing, see: https://github.com/c-hive/team-contribution-calendar/issues/55#issuecomment-582831326

**Comment by gomorizsolt** [comment]
> > package-lock.json is omitted for some reason
> 
> Because this is a package. It will run in different environments, it will be used by others who already have certain dependencies in their project. We must specify a range of dependencies we're compatible with, not exact versions. The lock file is used when e.g. a deployment of a website uses the exact same dependencies as the development version.
> 
> yarn/npm install may resolve to different things in different projects. Someone might specific `svgo = 1.3.1` in their package.json and wants to use this package. Then, yarn/npm must warn them that we're only compatible with 1.3.2 and up.

Thanks for putting this together and for the issue as well.

> This isn't an issue with svgson, please take a closer look at yarn.lock.

Yea, my bad. I don't know how come it's an issue with `svgson`.

- https://github.com/iest/babel-plugin-inline-svg/blob/master/package.json#L27 (`^1.0.3`, so it goes up to the next minor version)
- https://github.com/albinotonnina/parcel-plugin-inlinesvg/blob/master/package.json#L27 (`^1.0.3`, so it goes up to the next minor version)
- https://github.com/posthtml/htmlnano/blob/master/package.json#L40 (it's not a direct dependency, but the version is set to `^1.3.2`)
- https://github.com/ben-eb/postcss-svgo/blob/master/package.json#L59 (it's not a direct dependency and is even deprecated)

It's most likely to be an incompatibility with [`babel-plugin-inline-svg`](https://github.com/iest/babel-plugin-inline-svg) because executing `npm run build` with `svgo@1.3.1` exits with `Cannot set property 'multipassCount' of undefined`.

**Pull request closed without merging**
